### ISSUE TITLE
can't combine data

### ISSUE THREAD

**Issue by zbc1508** [geodynamics/citcoms#14]
Dear developer:
I have trouble combine data of example0:
lily@lily-MS-7D48:~/Citcoms/share/CitcomS/examples$ python2 autocombine.py localhost pid000089188 10
reading example0.coord,velo,visc.0.10.pasted
writing example0.cap00.10
Traceback (most recent call last):
  File "autocombine.py", line 155, in <module>
    optional_fields_EL, ncompositions)
  File "/home/lily/Citcoms/share/CitcomS/examples/batchcombine.py", line 106, in batchcombine
    batchpaste(datadir, datafile, fields, timestep, nodes)
  File "/home/lily/Citcoms/share/CitcomS/examples/batchcombine.py", line 87, in batchpaste
    pasteCitcomData.run(datadir, datafile, fields, rank, timestep, cwd)
  File "/home/lily/Citcoms/share/CitcomS/examples/pasteCitcomData.py", line 53, in run
    paste(datadir, datafile, fields, rank, step, f)
  File "/home/lily/Citcoms/share/CitcomS/examples/pasteCitcomData.py", line 68, in paste
    f = open_file(datadir, datafile, infix, rank, step)
  File "/home/lily/Citcoms/share/CitcomS/examples/pasteCitcomData.py", line 115, in open_file
    f = open(filename, 'r')
IOError: [Errno 2] No such file or directory: './example0.heating.0.10'
lily@lily-MS-7D48:~/Citcoms/share/CitcomS/examples$ 

My directory don't have file ".....heating", I don't know why?

**Comment by tan2** [comment]
The heating output is introduced in revision
7ca37a6c25611762a837e3dc34223e283d66aaac, but the heating file is outputted
only if the dissipation number is not 0.
You can change the file visual/autocombine.py, and remove the the red line
below.
This should fix your problem.


# default values for CitcomS input
defaults = {'output_format': 'ascii',
            'output_optional': 'surf,botm',
   'output_optional_EL': 'heating',   # remove temporarily
            'buoy_type': 1,
            'tracer_flavors': 2,

**Comment by zbc1508** [comment]
Thank you for your reply, professor! Thank you very much!
